#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 22 15:37:52 2021

@author: pageot
Validation Irrigation automatique parcelle all partenaires 
"""


import os
import sqlite3
import geopandas as geo 
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import cm
import csv
import numpy as np
import pandas as pd
import seaborn as sns 
import TEST_ANALYSE_SIGNATURE
import shapely.geometry as geom
import descartes
import pickle
from datetime import datetime, date, time, timezone
from scipy import *
from scipy import stats
from pylab import *
from sklearn.metrics import *
from sklearn.linear_model import LinearRegression

def predict(x):
   return slope * x + intercept


if __name__ == '__main__':
    d={}
    d["PC_disk"]="/run/media/pageot/Transcend/Yann_THESE/BESOIN_EAU/BESOIN_EAU/"
    d["PC_labo"]="/datalocal/vboxshare/THESE/BESOIN_EAU/"
    years=["2017"]

    
    # Input data si depth == GSM et PF_CC ==  BRUAND
    df_CACG=pd.read_csv(d["PC_disk"]+"TRAITEMENT/RUNS_SAMIR/RUN_CACG/CACG_init_ru_optim_P055_Fcover_fewi_De_Kr_days10_dose30_400_2500_irri_auto_soil/tab_resu_depth_GSM_UTS_PF_CC.csv")
    df_PKGC=pd.read_csv(d["PC_disk"]+"/TRAITEMENT/RUNS_SAMIR/RUN_PKGC/GERS/PKGC_init_ru_optim_P055_Fcover_fewi_De_Kr_days10_dose30_400_2500_irri_auto_soil/tab_resu_forcagemaxZr_p_data_GSM.csv",sep=',',encoding='latin-1',decimal=',')
    data_valid_PKGC=pd.read_csv(d["PC_disk"]+"/TRAITEMENT/SOIL/SOIL_RIGOU/Extract_RRP_Rigou_parcelle_PKCG_GERS_2017_UTS_maj.csv",index_col=[0],sep=';',encoding='latin-1',decimal=',')
    list_drop=[7,9,10,13,25,29,34,50,54,61,83,90,98]
    data_valid_PKGC =data_valid_PKGC[-data_valid_PKGC["ID"].isin(list_drop)]
    
    
    
    #  SI maxZr == RUM inverser et PF_CC = BRUAND
    df_CAGC= pd.read_csv(d["PC_disk"]+"TRAITEMENT/RUNS_SAMIR/RUN_CACG/maxZr_rum/tab_resu_CACG_maxZr_inversion_RUM_2017.csv")
    df_PKGC=pd.read_csv(d["PC_disk"]+"TRAITEMENT/RUNS_SAMIR/RUN_PKGC/GERS/maxZr_rum/tab_resu_PKGC_maxZr_inversion_RUM.csv")
    
    
    #  SI maxAr= GSM et PF_CC == GSM 
    #  Pas lancer pour CACG